name: deploy-springboot-appln
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Setup JDK
        uses: actions/setup-java@v4
        with: 
          distribution: 'temurin'
          java-version: '17'
      - name: Build
        run: mvn clean install
    

  deploy:
    needs: ['build']
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        run: echo 'Deployment Successful'


      
