name: deploy-springboot-appln
on: workflow_dispatch
jobs:
  pre-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Setup JDK
        uses: actions/setup-java@v4
        with: 
          distribution: 'tamurin'
          java-version: '17'
  
  build: 
    needs: pre-build
    runs-on: ubuntu-latest
    steps:
      - name: Build
        run: mvn clean install

  deploy:
    needs: ['build','pre-build']
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        run: echo 'Deployment Successful'


      
